export interface ColumnSchema {
    name: string;
    type: string;
    isPrimaryKey: boolean;
    isNullable: boolean;
    isForeignKey: boolean;
    defaultValue?: string | null;
    isUnique?: boolean;
    isAutoGenerated?: boolean; 
  }