// src/api/types.ts

/**
 * Defines the structure of the schema information expected
 * for a single column from the backend API.
 */
export interface ApiColumnSchema {
    name: string;          // Name of the column
    type: string;          // Database type (e.g., 'TEXT', 'INTEGER', 'NUMERIC(10,2)', 'BOOLEAN', 'TIMESTAMP WITH TIME ZONE')
    isPrimaryKey: boolean; // True if this column is part of the primary key
    isNullable: boolean;   // True if the column allows NULL values
    isForeignKey: boolean; // True if this column is a foreign key
    // --- Optional but Recommended Backend Additions ---
    isAutoGenerated?: boolean; // True if the value is generated by DB (e.g., SERIAL, auto-increment, UUID default) - Helps frontend forms
    // foreignKeyInfo?: { // More detailed FK info if available
    //   referencedTable: string;
    //   referencedColumn: string;
    // };
    // defaultValue?: any; // Default value defined in the database schema
    // isUnique?: boolean;   // If the column has a UNIQUE constraint
  }
  
  /**
   * Defines the structure of the response when fetching
   * paginated data for a table.
   */
  export interface ApiFetchDataResponse {
    data: any[];   // Array of row objects
    total: number; // Total number of rows matching the query (for pagination)
  }
  
  /**
   * Defines the structure of the payload when creating
   * a new column via the API.
   */
  export interface NewColumnPayload {
    name: string;        // New column's name
    type: string;        // New column's data type (matching backend/DB supported types)
    isNullable?: boolean; // Optional: Default often depends on DB (usually true unless specified)
    defaultValue?: any; // Optional: Default value
    isUnique?: boolean;   // Optional: Add unique constraint?
    // Add other constraints/properties as needed (e.g., character limit for VARCHAR)
  }
  
  // Add other specific request/response types if your API uses them
  // e.g., interface ApiResponseSuccess { success: boolean; data?: any; }
  // e.g., interface ApiResponseError { success: boolean; message: string; }

  export interface LoginCredentials {
    email: string;
    password: string;
  }
  
  /**
   * Credentials required for user signup.
   */
  export interface SignupCredentials {
    username: string;
    email: string;
    password: string;
  }